In [1]:
pip install numpy

   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   -- ------------------------------------- 0.8/12.6 MB 3.9 MB/s eta 0:00:04
   ----- ---------------------------------- 1.8/12.6 MB 3.9 MB/s eta 0:00:03
   -------- ------------------------------- 2.6/12.6 MB 2.3 MB/s eta 0:00:05
   ------------- -------------------------- 4.2/12.6 MB 2.9 MB/s eta 0:00:03
   ------------------ --------------------- 5.8/12.6 MB 3.0 MB/s eta 0:00:03
   -------------------- ------------------- 6.6/12.6 MB 3.0 MB/s eta 0:00:03
   ----------------------- ---------------- 7.3/12.6 MB 2.9 MB/s eta 0:00:02
   ------------------------- -------------- 7.9/12.6 MB 2.9 MB/s eta 0:00:02
   -------------------------- ------------- 8.4/12.6 MB 2.9 MB/s eta 0:00:02
   ---------------------------- ----------- 8.9/12.6 MB 2.7 MB/s eta 0:00:02
   ------------------------------ --------- 9.4/12.6 MB 2.7 MB/s eta 0:00:02
   ------------------------------ --------- 9.7/12.6 MB 2.7 MB/s eta 0:00:02
   ---

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


In [2]:
import numpy as np

In [2]:
import numpy as np
arr=np.array([1, 2, 3, 4, 5]) 
print(arr)

[1 2 3 4 5]


In [3]:
print(np.ones((3, 4)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [4]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:
print(np.random.randint(1,100, size=(4,4)))

[[22 70 60 90]
 [88 62  8 38]
 [68  9 61 91]
 [30 63 93 48]]


In [7]:
print(np.arange(0,20,2))

[ 0  2  4  6  8 10 12 14 16 18]


In [2]:
import numpy as np
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]


In [3]:
arr=np.array([10,20,30,40])
print(np.sum(arr))
print(np.mean(arr))
print(np.std(arr))
print(np.var(arr))
print(np.min(arr))
print(np.max(arr))

100
25.0
11.180339887498949
125.0
10
40


In [4]:
print(np.random.choice([10,20,30], size=4))

[10 20 20 20]


In [5]:
#shuffle
arr=np.arange(50)
np.random.shuffle(arr)
print(arr)

[26 39 12 16  4 21 38 42 15 47 29 45 49 20 19  9 22 32 37 11 18  8 24 10
  1 31 48  7 27  3 13 35 43 14 46  2 23 17 36 28 44 33  5 40 34  6  0 25
 30 41]


In [6]:
#boolean indexing
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr[arr > 5])

[6 7 8 9]


In [9]:
#where
arr=np.array([10,20,30,40])
print(np.where(arr > 30))

(array([3]),)


In [ ]:
#sorting

In [1]:
pip install pandas

   ---------------------------------------- 0.0/10.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/10.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/10.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/10.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/10.0 MB ? eta -:--:--
   - -------------------------------------- 0.3/10.0 MB ? eta -:--:--
   - -------------------------------------- 0.3/10.0 MB ? eta -:--:--
   - -------------------------------------- 0.3/10.0 MB ? eta -:--:--
   - -------------------------------------- 0.3/10.0 MB ? eta -:--:--
   - -------------------------------------- 0.3/10.0 MB ? eta -:--:--
   - -------------------------------------- 0.3/10.0 MB ? eta -:--:--
   -- ------------------------------------- 0.5/10.0 MB 195.7 kB/s eta 0:00:49
   -- ------------------------------------- 0.5/10.0 MB 195.7 kB/s eta 0:00:49
   -- ------------------------------------- 0.5/10.0 MB 195.7 kB/s eta 0

In [2]:
import pandas as pd

In [3]:
import pandas as pd
marks = pd.Series([90, 80, 70, 60, 50])
print(marks)

0    90
1    80
2    70
3    60
4    50
dtype: int64


In [5]:
import pandas as pd
data={
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Age": [25, 30, 35, 40],
    "marks": [90, 80, 70, 60]
}
df=pd.DataFrame(data)

In [6]:
df

,Name,Age,marks
0,Alice,25,90
1,Bob,30,80
2,Charlie,35,70
3,David,40,60


In [8]:
pip install requests


   ---------------------------------------- 0/5 [urllib3]
   ---------------------------------------- 0/5 [urllib3]
   -------- ------------------------------- 1/5 [idna]
   -------- ------------------------------- 1/5 [idna]
   ---------------- ----------------------- 2/5 [charset_normalizer]
   -------------------------------- ------- 4/5 [requests]
   -------------------------------- ------- 4/5 [requests]
   ---------------------------------------- 5/5 [requests]

Note: you may need to restart the kernel to use updated packages.


  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


In [10]:
import requests
from io import StringIO

In [11]:
pd.read_csv(StringIO(requests.get("https://people.sc.fsu.edu/~jburkardt/data/csv/hw_200.csv").text))

,Index,"Height(Inches)""","""Weight(Pounds)"""
0,1,65.78,112.99
1,2,71.52,136.49
2,3,69.40,153.03
3,4,68.22,142.34
4,5,67.79,144.30
...,...,...,...
195,196,65.80,120.84
196,197,66.11,115.78
197,198,68.24,128.30
198,199,68.02,127.47


In [13]:
url="https://people.sc.fsu.edu/~jburkardt/data/csv/hw_200.csv"
headers ={"UnicodeTranslateError": "ignore"}

In [2]:
import numpy as np
import pandas as pd

In [ ]:
data =pd.read_csv